backend = "xrender";
vsync = true;

fading = true;          # Pastikan ini aktif (true)
fade-delta = 2;         # Kurangi nilai ini untuk animasi lebih cepat (default: 10)
fade-in-step = 0.05;    # Tingkatkan nilai ini untuk animasi masuk lebih cepat (default: 0.03)
fade-out-step = 0.05;   # Tingkatkan nilai ini untuk animasi keluar lebih cepat (default: 0.03)
