[colors]
; --- GRUVBOX DARK HARD PALETTE ---

base = #1d2021
mantle = #282828
crust = #11111b
text = #ebdbb2
subtext0 = #a89984
subtext1 = #928374

surface0 = #3c3836
surface1 = #504945
surface2 = #665c54
overlay0 = #7c6f64
overlay1 = #a89984
overlay2 = #ebdbb2

blue = #458588
lavender = #b16286
sapphire = #458588
sky = #689d6a
teal = #689d6a
green = #98971a
yellow = #d79921
peach = #d65d0e
maroon = #cc241d
red = #cc241d
mauve = #b16286
pink = #b16286
flamingo = #cc241d
rosewater = #d79921

transparent = #00000000

;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║  ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║  ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║ ██║██║ ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = ${colors.mantle}
background-alt = ${colors.surface0}
foreground = ${colors.text}
primary = ${colors.blue}
secondary = ${colors.surface1}
alert = ${colors.red}
disabled = ${colors.subtext1}

[bar/toph]
monitor = ${env:MONITOR:}
width = 100%
height = 25pt
radius = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

bottom = false

line-size = 6pt

#border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.yellow}

font-0 = CaskaydiaCove Nerd Font:size=12;6

modules-left = xworkspaces xwindow
modules-right = pulseaudio battery memory cpu wlan date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.blue}
label-active-foreground = ${colors.base}
label-active-underline= ${colors.blue}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#${colors.yellow}}%mountpoint%%{F-}%percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[module/battery]
type = internal/battery
format-prefix = "BAT "
format-prefix-foreground = ${colors.primary}
full-at = 99
format-charging = <animation-charging> <label-charging>
animation-charging-0 =
animation-charging-1 =
animation-charging-2 =
animation-charging-3 =
animation-charging-4 =
; Framerate in milliseconds
animation-charging-framerate = 750
animation-charging-foreground = ${colors.orange}
format-discharging = <ramp-capacity> <label-discharging>
ramp-capacity-0 =
ramp-capacity-1 =
ramp-capacity-2 =
ramp-capacity-3 =
ramp-capacity-4 =
low-at = 5
battery = BAT1
adapter = ACAD
poll-interval = 5

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
; yellow = #d79921
; grey = #a89984
label-disconnected = %{F#d79921}%ifname%%{F#a89984} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
; Gunakan kode heksadesimal langsung untuk yellow Gruvbox di sini
; yellow = #d79921
label-connected = %{F#d79921}%ifname%%{F-}%essid%

[module/eth]
inherit = network-base
interface-type = wired
; yellow = #d79921
label-connected = %{F#d79921}%ifname%%{F-}%local_ip%

[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
