preload = /home/ditya/Pictures/Wallpapers/salisbury_cathedral_from_lower_marsh_close_1937.1.108.jpg
wallpaper = LVDS-1,/home/ditya/Pictures/Wallpapers/salisbury_cathedral_from_lower_marsh_close_1937.1.108.jpg
wallpaper = VGA-1,/home/ditya/Pictures/Wallpapers/salisbury_cathedral_from_lower_marsh_close_1937.1.108.jpg
