preload = /home/ditya/Pictures/Wallpapers/constantinopel.jpg
wallpaper = LVDS-1,/home/ditya/Pictures/Wallpapers/constantinopel.jpg
wallpaper = VGA-1,/home/ditya/Pictures/Wallpapers/constantinopel.jpg
