preload = /home/ditya/dotfiles/wallpapers/Pictures/Wallpapers/europeana-7g4jI-KdN-s-unsplash.jpg
wallpaper = LVDS-1,/home/ditya/dotfiles/wallpapers/Pictures/Wallpapers/europeana-7g4jI-KdN-s-unsplash.jpg
wallpaper = VGA-1,/home/ditya/dotfiles/wallpapers/Pictures/Wallpapers/europeana-7g4jI-KdN-s-unsplash.jpg
