#!/bin/bash

# === CONFIG ===
COLORS_JSON="$HOME/.cache/wal/colors.json"
HYPR_COLORS_CONF="$HOME/.config/hypr/hyprland-colors.conf"

# === CHECK FILE ===
if [ ! -f "$COLORS_JSON" ]; then
  echo "[ERR] Pywal colors.json not found."
  exit 1
fi

# === EXTRACT COLORS ===
get_color() {
  jq -r "$1" "$COLORS_JSON" | sed 's/#//'
}

FOREGROUND=$(get_color '.special.foreground')
BACKGROUND=$(get_color '.special.background')
CURSOR=$(get_color '.special.cursor')

COLOR0=$(get_color '.colors.color0')
COLOR1=$(get_color '.colors.color1')
COLOR2=$(get_color '.colors.color2')
COLOR3=$(get_color '.colors.color3')
COLOR4=$(get_color '.colors.color4')
COLOR5=$(get_color '.colors.color5')
COLOR6=$(get_color '.colors.color6')
COLOR7=$(get_color '.colors.color7')
COLOR8=$(get_color '.colors.color8')
COLOR9=$(get_color '.colors.color9')
COLOR10=$(get_color '.colors.color10')
COLOR11=$(get_color '.colors.color11')
COLOR12=$(get_color '.colors.color12')
COLOR13=$(get_color '.colors.color13')
COLOR14=$(get_color '.colors.color14')
COLOR15=$(get_color '.colors.color15')

# === GENERATE rgba(...) values ===
rgba() {
  echo "rgba(${1}ff)" # solid color
}

rgba_trans() {
  echo "rgba(${1}cc)" # semi-transparent (alpha = 80%)
}

# === WRITE TO CONFIG ===
cat >"$HYPR_COLORS_CONF" <<EOF
# Auto-generated by update-hypr-colors.sh

general {
  col.active_border = $(rgba $COLOR6)
  col.inactive_border = $(rgba $BACKGROUND)
}
EOF

echo "[OK] Hyprland color config generated at $HYPR_COLORS_CONF"

# === Reload Hyprland ===
hyprctl reload
echo "[OK] Hyprland reloaded"
